### ISSUE TITLE
 LoadError: type NullAttr has no field size on Apple M1 (ARM) architecture

### ISSUE THREAD

**Issue by kellertuer** [chriselrod/VectorizationBase.jl#21]
I am not 100% sure this is the right place, but the same tests run fine on my older machine but fail on my new MacBook Pro with the M1 chip (so an ARM architecture). The error message reads

```
ERROR: LoadError: LoadError: type NullAttr has no field size
Stacktrace:
 [1] getproperty(::Hwloc.NullAttr, ::Symbol) at ./Base.jl:33
 [2] top-level scope at /Users/ronny/.julia/packages/VectorizationBase/26Yla/src/topology.jl:8
 [3] include(::Function, ::Module, ::String) at ./Base.jl:380
 [4] include at ./Base.jl:368 [inlined]
 [5] include(::String) at /Users/ronny/.julia/packages/VectorizationBase/26Yla/src/VectorizationBase.jl:1
 [6] top-level scope at /Users/ronny/.julia/packages/VectorizationBase/26Yla/src/VectorizationBase.jl:270
 [7] include(::Function, ::Module, ::String) at ./Base.jl:380
 [8] include(::Module, ::String) at ./Base.jl:368
 [9] top-level scope at none:2
 [10] eval at ./boot.jl:331 [inlined]
 [11] eval(::Expr) at ./client.jl:467
 [12] top-level scope at ./none:3
```
i.e. I have
```
ERROR: LoadError: Failed to precompile VectorizationBase [3d5dd08c-fd9d-11e8-17fa-ed2836048c2f] to /Users/ronny/.julia/compiled/v1.5/VectorizationBase/Dto5m_1dTjA.ji.
```
when actually trying to compile `DiffEqBase` (6.44.3). So to recreate this, after `] add DiffEqbase` doing `using DiffEqBase` causes this error for example.

If I can provide any further information, let me know.

__edit__: Oh sorry only checked the ReadMe a little late – maybe the question could also be: Do you plan to support non x86 architectures?

**Comment by chriselrod** [comment]
I should update the README. Yes, I plan on supporting non-x86, and the Nvidia Jetson has been working for a while. Might even be better to just delete the current (out of date) README altogether.

A new release should be out in about half an hour. Mind checking if using VectorizationBase 0.13.6 fixes the problem?

More generally, on non-x86 support, it'd help to actually have code to describe the hardware in a meaningful way.
For ARM, it should check for NEON, SVE, and SVE2 support.
I think, but am not sure, that with each of these there are 32 named floating point registers?

LoopVectorization should also probably get explicit M1 support, because the cost modelling for the M1 will probably look quite different than from the current gen x86 CPUs. E.g., it's capable of 4 floating point operations per cycle instead of just 2.
If the latency for instructions to complete is similar (is it? probably), that would mean it might want a lot more unrolling for optimal performance. 
But maybe its out of order is so much better, it only needs this unrolling to cut dependency chains, and otherwise it's actually better without excess unrolling.
It could use some performance tuning.

I should get around to writing some auto-tuning scripts that people with different arches can run and share their results, so that it's easier to have optimized values for different architectures.

**Comment by kellertuer** [comment]
Wow! Super nice! This did not only solve my test case which failed, it was even the only error that I had in those tests.

Thank you for your comprehensive explanation. I am not sure about performance (and definitely not an expert on that) but the new version has resolved my error.

**Comment by chriselrod** [comment]
Great!
If you want to try to help with performance, you could file a new issue here, and for starters, show the results of:
```julia
using Libdl
llvmlib = VERSION ≥ v"1.6.0-DEV.1429" ? Libdl.dlopen(Base.libllvm_path()) : Libdl.dlopen(only(filter(lib->occursin(r"LLVM\b", basename(lib)), Libdl.dllist())));
gethostcpufeatures = Libdl.dlsym(llvmlib, :LLVMGetHostCPUFeatures);
features_cstring = ccall(gethostcpufeatures, Cstring, ());
features = filter(ext -> (m = match(r"\d", ext); isnothing(m) ? true : m.offset != 2 ), split(unsafe_string(features_cstring), ','));
println(features)
```
E.g,
on x86_64
```julia
julia> println(features)
SubString{String}["+sse2", "-tsxldtrk", "+cx16", "+sahf", "-tbm", "+avx512ifma", "+sha", "+gfni", "-fma4", "+vpclmulqdq", "+prfchw", "+bmi2", "-cldemote", "+fsgsbase", "-ptwrite", "-amx-tile", "-avx512bf16
", "+popcnt", "+aes", "+avx512bitalg", "+movdiri", "+xsaves", "-avx512er", "+xsavec", "+avx512vnni", "-amx-bf16", "+avx512vpopcntdq", "-pconfig", "+clwb", "+avx512f", "-clzero", "+pku", "+mmx", "-lwp", "+r
dpid", "-xop", "+rdseed", "-waitpkg", "+movdir64b", "-sse4a", "+avx512bw", "+clflushopt", "+xsave", "+avx512vbmi2", "+avx512vl", "-serialize", "+invpcid", "+avx512cd", "+avx", "+vaes", "+cx8", "+fma", "-rtm", "+bmi", "-enqcmd", "+rdrnd", "-mwaitx", "+sse4.1", "+sse4.2", "+avx2", "+fxsr", "-wbnoinvd", "+sse", "+lzcnt", "+pclmul", "-prefetchwt1", "+f16c", "+ssse3", "-sgx", "+shstk", "+cmov", "+avx512vbmi", "-amx-int8", "+movbe", "+avx512vp2intersect", "+xsaveopt", "+avx512dq", "+adx", "-avx512pf", "+sse3"]
```
Basically, I want to know what is actually being defined [here](https://github.com/chriselrod/VectorizationBase.jl/blob/be4f907c55e814a74fec25d552c6a0fa1f82a360/src/cpu_info_x86_llvm.jl#L19-L21).

**Comment by turingtest37** [comment]
Sorry I'm a bit late getting to a reply. Ran your code on my Jetson Nano.
Pretty scarce on features!

julia> using Libdl
> julia> llvmlib = VERSION ≥ v"1.6.0-DEV.1429" ?
> Libdl.dlopen(Base.libllvm_path()) :
> Libdl.dlopen(only(filter(lib->occursin(r"LLVM\b", basename(lib)),
> Libdl.dllist())));
> julia> gethostcpufeatures = Libdl.dlsym(llvmlib, :LLVMGetHostCPUFeatures);
> julia> features_cstring = ccall(gethostcpufeatures, Cstring, ());
> julia> features = filter(ext -> (m = match(r"\d", ext); isnothing(m) ?
> true : m.offset != 2 ), split(unsafe_string(features_cstring), ','));
> julia> println(features)
> SubString{String}["+neon", "+fp-armv8", "+crypto", "+crc"]
>
>
Not much to optimize I guess??
